// 自动生成：四级真题阅读系统（词块法）的 24 步任务数据
// 来源：GitHub wamich/english-exem-md · 2023年6月/12月四级真题
// 一篇 = 一步；在修仙看板里逐篇推进，完成给修为，支持一天一篇。
import type { TaskStep } from "./task-model";

export const ENGLISH_READING_TASK_ID = "english-reading";

export const ENGLISH_READING_STEPS: TaskStep[] = [
  {
    id: "eng_1",
    title: "学年制度",
    description: "2023.06 · 第2套 · Section C Passage Two · 校园类",
    goal: "把本篇真题贴给 AI 逐句讲解词块，学完后让 AI 生成词块标注版与总结，并积累进 Obsidian 搭配本。",
    minutes: 25,
    xp: 35,
    checklist: ["复制第 1 段发给我，听词块讲解", "逐段学完，把词块积累到搭配本", "学完一篇后让 AI 生成标注版 HTML"],
    guidance: "打开 all-articles.html 选本篇，点段落复制发给我；一篇学完我出标注复习版。",
  },
  {
    id: "eng_2",
    title: "语音网络 The spoken web",
    description: "2023.06 · 第1套 · Section B · 科技类",
    goal: "把本篇真题贴给 AI 逐句讲解词块，学完后让 AI 生成词块标注版与总结，并积累进 Obsidian 搭配本。",
    minutes: 56,
    xp: 70,
    checklist: ["复制第 1 段发给我，听词块讲解", "逐段学完，把词块积累到搭配本", "学完一篇后让 AI 生成标注版 HTML"],
    guidance: "打开 all-articles.html 选本篇，点段落复制发给我；一篇学完我出标注复习版。",
  },
  {
    id: "eng_3",
    title: "多任务与科技",
    description: "2023.12 · 第2套 · Section C Passage Two · 科技类",
    goal: "把本篇真题贴给 AI 逐句讲解词块，学完后让 AI 生成词块标注版与总结，并积累进 Obsidian 搭配本。",
    minutes: 25,
    xp: 35,
    checklist: ["复制第 1 段发给我，听词块讲解", "逐段学完，把词块积累到搭配本", "学完一篇后让 AI 生成标注版 HTML"],
    guidance: "打开 all-articles.html 选本篇，点段落复制发给我；一篇学完我出标注复习版。",
  },
  {
    id: "eng_4",
    title: "青少年与社交网络",
    description: "2023.12 · 第3套 · Section B · 科技类",
    goal: "把本篇真题贴给 AI 逐句讲解词块，学完后让 AI 生成词块标注版与总结，并积累进 Obsidian 搭配本。",
    minutes: 56,
    xp: 70,
    checklist: ["复制第 1 段发给我，听词块讲解", "逐段学完，把词块积累到搭配本", "学完一篇后让 AI 生成标注版 HTML"],
    guidance: "打开 all-articles.html 选本篇，点段落复制发给我；一篇学完我出标注复习版。",
  },
  {
    id: "eng_5",
    title: "美国住房危机",
    description: "2023.06 · 第1套 · Section C Passage One · 社会类·城市与社会",
    goal: "把本篇真题贴给 AI 逐句讲解词块，学完后让 AI 生成词块标注版与总结，并积累进 Obsidian 搭配本。",
    minutes: 25,
    xp: 35,
    checklist: ["复制第 1 段发给我，听词块讲解", "逐段学完，把词块积累到搭配本", "学完一篇后让 AI 生成标注版 HTML"],
    guidance: "打开 all-articles.html 选本篇，点段落复制发给我；一篇学完我出标注复习版。",
  },
  {
    id: "eng_6",
    title: "洛杉矶无家可归",
    description: "2023.06 · 第3套 · Section C Passage Two · 社会类·城市与社会",
    goal: "把本篇真题贴给 AI 逐句讲解词块，学完后让 AI 生成词块标注版与总结，并积累进 Obsidian 搭配本。",
    minutes: 25,
    xp: 35,
    checklist: ["复制第 1 段发给我，听词块讲解", "逐段学完，把词块积累到搭配本", "学完一篇后让 AI 生成标注版 HTML"],
    guidance: "打开 all-articles.html 选本篇，点段落复制发给我；一篇学完我出标注复习版。",
  },
  {
    id: "eng_7",
    title: "创业者野心",
    description: "2023.06 · 第1套 · Section C Passage Two · 社会类·商业与职场",
    goal: "把本篇真题贴给 AI 逐句讲解词块，学完后让 AI 生成词块标注版与总结，并积累进 Obsidian 搭配本。",
    minutes: 32,
    xp: 40,
    checklist: ["复制第 1 段发给我，听词块讲解", "逐段学完，把词块积累到搭配本", "学完一篇后让 AI 生成标注版 HTML"],
    guidance: "打开 all-articles.html 选本篇，点段落复制发给我；一篇学完我出标注复习版。",
  },
  {
    id: "eng_8",
    title: "超市与电商",
    description: "2023.06 · 第2套 · Section C Passage One · 社会类·商业与职场",
    goal: "把本篇真题贴给 AI 逐句讲解词块，学完后让 AI 生成词块标注版与总结，并积累进 Obsidian 搭配本。",
    minutes: 25,
    xp: 35,
    checklist: ["复制第 1 段发给我，听词块讲解", "逐段学完，把词块积累到搭配本", "学完一篇后让 AI 生成标注版 HTML"],
    guidance: "打开 all-articles.html 选本篇，点段落复制发给我；一篇学完我出标注复习版。",
  },
  {
    id: "eng_9",
    title: "团队建设",
    description: "2023.06 · 第3套 · Section C Passage One · 社会类·商业与职场",
    goal: "把本篇真题贴给 AI 逐句讲解词块，学完后让 AI 生成词块标注版与总结，并积累进 Obsidian 搭配本。",
    minutes: 32,
    xp: 40,
    checklist: ["复制第 1 段发给我，听词块讲解", "逐段学完，把词块积累到搭配本", "学完一篇后让 AI 生成标注版 HTML"],
    guidance: "打开 all-articles.html 选本篇，点段落复制发给我；一篇学完我出标注复习版。",
  },
  {
    id: "eng_10",
    title: "性别与机票",
    description: "2023.12 · 第1套 · Section C Passage Two · 社会类·商业与职场",
    goal: "把本篇真题贴给 AI 逐句讲解词块，学完后让 AI 生成词块标注版与总结，并积累进 Obsidian 搭配本。",
    minutes: 32,
    xp: 40,
    checklist: ["复制第 1 段发给我，听词块讲解", "逐段学完，把词块积累到搭配本", "学完一篇后让 AI 生成标注版 HTML"],
    guidance: "打开 all-articles.html 选本篇，点段落复制发给我；一篇学完我出标注复习版。",
  },
  {
    id: "eng_11",
    title: "竞争与创业",
    description: "2023.12 · 第2套 · Section C Passage One · 社会类·商业与职场",
    goal: "把本篇真题贴给 AI 逐句讲解词块，学完后让 AI 生成词块标注版与总结，并积累进 Obsidian 搭配本。",
    minutes: 25,
    xp: 35,
    checklist: ["复制第 1 段发给我，听词块讲解", "逐段学完，把词块积累到搭配本", "学完一篇后让 AI 生成标注版 HTML"],
    guidance: "打开 all-articles.html 选本篇，点段落复制发给我；一篇学完我出标注复习版。",
  },
  {
    id: "eng_12",
    title: "商业直觉",
    description: "2023.12 · 第3套 · Section C Passage Two · 社会类·商业与职场",
    goal: "把本篇真题贴给 AI 逐句讲解词块，学完后让 AI 生成词块标注版与总结，并积累进 Obsidian 搭配本。",
    minutes: 28,
    xp: 35,
    checklist: ["复制第 1 段发给我，听词块讲解", "逐段学完，把词块积累到搭配本", "学完一篇后让 AI 生成标注版 HTML"],
    guidance: "打开 all-articles.html 选本篇，点段落复制发给我；一篇学完我出标注复习版。",
  },
  {
    id: "eng_13",
    title: "F1 赛车与美国市场",
    description: "2023.06 · 第2套 · Section B · 社会类·体育与商业",
    goal: "把本篇真题贴给 AI 逐句讲解词块，学完后让 AI 生成词块标注版与总结，并积累进 Obsidian 搭配本。",
    minutes: 60,
    xp: 75,
    checklist: ["复制第 1 段发给我，听词块讲解", "逐段学完，把词块积累到搭配本", "学完一篇后让 AI 生成标注版 HTML"],
    guidance: "打开 all-articles.html 选本篇，点段落复制发给我；一篇学完我出标注复习版。",
  },
  {
    id: "eng_14",
    title: "散步与情绪",
    description: "2023.06 · 第3套 · Section A · 社会类·健康与心理",
    goal: "把本篇真题贴给 AI 逐句讲解词块，学完后让 AI 生成词块标注版与总结，并积累进 Obsidian 搭配本。",
    minutes: 25,
    xp: 35,
    checklist: ["复制第 1 段发给我，听词块讲解", "逐段学完，把词块积累到搭配本", "学完一篇后让 AI 生成标注版 HTML"],
    guidance: "打开 all-articles.html 选本篇，点段落复制发给我；一篇学完我出标注复习版。",
  },
  {
    id: "eng_15",
    title: "运动与健康",
    description: "2023.12 · 第1套 · Section A · 社会类·健康与心理",
    goal: "把本篇真题贴给 AI 逐句讲解词块，学完后让 AI 生成词块标注版与总结，并积累进 Obsidian 搭配本。",
    minutes: 25,
    xp: 35,
    checklist: ["复制第 1 段发给我，听词块讲解", "逐段学完，把词块积累到搭配本", "学完一篇后让 AI 生成标注版 HTML"],
    guidance: "打开 all-articles.html 选本篇，点段落复制发给我；一篇学完我出标注复习版。",
  },
  {
    id: "eng_16",
    title: "忙碌文化",
    description: "2023.12 · 第1套 · Section C Passage One · 社会类·健康与心理",
    goal: "把本篇真题贴给 AI 逐句讲解词块，学完后让 AI 生成词块标注版与总结，并积累进 Obsidian 搭配本。",
    minutes: 25,
    xp: 35,
    checklist: ["复制第 1 段发给我，听词块讲解", "逐段学完，把词块积累到搭配本", "学完一篇后让 AI 生成标注版 HTML"],
    guidance: "打开 all-articles.html 选本篇，点段落复制发给我；一篇学完我出标注复习版。",
  },
  {
    id: "eng_17",
    title: "健康习惯",
    description: "2023.12 · 第3套 · Section A · 社会类·健康与心理",
    goal: "把本篇真题贴给 AI 逐句讲解词块，学完后让 AI 生成词块标注版与总结，并积累进 Obsidian 搭配本。",
    minutes: 25,
    xp: 35,
    checklist: ["复制第 1 段发给我，听词块讲解", "逐段学完，把词块积累到搭配本", "学完一篇后让 AI 生成标注版 HTML"],
    guidance: "打开 all-articles.html 选本篇，点段落复制发给我；一篇学完我出标注复习版。",
  },
  {
    id: "eng_18",
    title: "舞狮传统文化",
    description: "2023.06 · 第3套 · Section B · 社会类·文化与传统",
    goal: "把本篇真题贴给 AI 逐句讲解词块，学完后让 AI 生成词块标注版与总结，并积累进 Obsidian 搭配本。",
    minutes: 52,
    xp: 65,
    checklist: ["复制第 1 段发给我，听词块讲解", "逐段学完，把词块积累到搭配本", "学完一篇后让 AI 生成标注版 HTML"],
    guidance: "打开 all-articles.html 选本篇，点段落复制发给我；一篇学完我出标注复习版。",
  },
  {
    id: "eng_19",
    title: "家庭与工作效率",
    description: "2023.12 · 第2套 · Section A · 社会类·家庭与生活",
    goal: "把本篇真题贴给 AI 逐句讲解词块，学完后让 AI 生成词块标注版与总结，并积累进 Obsidian 搭配本。",
    minutes: 25,
    xp: 35,
    checklist: ["复制第 1 段发给我，听词块讲解", "逐段学完，把词块积累到搭配本", "学完一篇后让 AI 生成标注版 HTML"],
    guidance: "打开 all-articles.html 选本篇，点段落复制发给我；一篇学完我出标注复习版。",
  },
  {
    id: "eng_20",
    title: "陪产假与性别",
    description: "2023.12 · 第2套 · Section B · 社会类·家庭与生活",
    goal: "把本篇真题贴给 AI 逐句讲解词块，学完后让 AI 生成词块标注版与总结，并积累进 Obsidian 搭配本。",
    minutes: 68,
    xp: 85,
    checklist: ["复制第 1 段发给我，听词块讲解", "逐段学完，把词块积累到搭配本", "学完一篇后让 AI 生成标注版 HTML"],
    guidance: "打开 all-articles.html 选本篇，点段落复制发给我；一篇学完我出标注复习版。",
  },
  {
    id: "eng_21",
    title: "赛马 Red Rum",
    description: "2023.12 · 第3套 · Section C Passage One · 社会类·体育与文化",
    goal: "把本篇真题贴给 AI 逐句讲解词块，学完后让 AI 生成词块标注版与总结，并积累进 Obsidian 搭配本。",
    minutes: 25,
    xp: 35,
    checklist: ["复制第 1 段发给我，听词块讲解", "逐段学完，把词块积累到搭配本", "学完一篇后让 AI 生成标注版 HTML"],
    guidance: "打开 all-articles.html 选本篇，点段落复制发给我；一篇学完我出标注复习版。",
  },
  {
    id: "eng_22",
    title: "棉花与服装生产",
    description: "2023.06 · 第1套 · Section A · 环境类",
    goal: "把本篇真题贴给 AI 逐句讲解词块，学完后让 AI 生成词块标注版与总结，并积累进 Obsidian 搭配本。",
    minutes: 25,
    xp: 35,
    checklist: ["复制第 1 段发给我，听词块讲解", "逐段学完，把词块积累到搭配本", "学完一篇后让 AI 生成标注版 HTML"],
    guidance: "打开 all-articles.html 选本篇，点段落复制发给我；一篇学完我出标注复习版。",
  },
  {
    id: "eng_23",
    title: "摩洛哥太阳能",
    description: "2023.06 · 第2套 · Section A · 环境类",
    goal: "把本篇真题贴给 AI 逐句讲解词块，学完后让 AI 生成词块标注版与总结，并积累进 Obsidian 搭配本。",
    minutes: 25,
    xp: 35,
    checklist: ["复制第 1 段发给我，听词块讲解", "逐段学完，把词块积累到搭配本", "学完一篇后让 AI 生成标注版 HTML"],
    guidance: "打开 all-articles.html 选本篇，点段落复制发给我；一篇学完我出标注复习版。",
  },
  {
    id: "eng_24",
    title: "气候变化与食物",
    description: "2023.12 · 第1套 · Section B · 环境类",
    goal: "把本篇真题贴给 AI 逐句讲解词块，学完后让 AI 生成词块标注版与总结，并积累进 Obsidian 搭配本。",
    minutes: 52,
    xp: 65,
    checklist: ["复制第 1 段发给我，听词块讲解", "逐段学完，把词块积累到搭配本", "学完一篇后让 AI 生成标注版 HTML"],
    guidance: "打开 all-articles.html 选本篇，点段落复制发给我；一篇学完我出标注复习版。",
  },
];
